#!/usr/bin/env python

# Simple program to demonstrate the usage of the Here geocoder client

import geocoding.clients
import sys

if len(sys.argv) < 4:
    print("""Usage: %s APP_ID APP_CODE "SEARCH_QUERY" """ % sys.argv[0])
    exit(1)

APP_ID = sys.argv[1]
APP_CODE = sys.argv[2]
searchtext = sys.argv[3]

client = geocoding.clients.HereGeocoderClient(APP_ID, APP_CODE)
client.issue_query(searchtext)
coords = client.get_coordinates()
print(coords)

exit(0)