#!/usr/bin/env python

import http.server
import geocoding.handlers
import geocoding.clients

BIND_ADDRESS = ''
BIND_PORT = 8888

SERVER_ADDRESS = (BIND_ADDRESS, BIND_PORT)

if __name__ == "__main__":
    print("Starting Geo Coding Service...")
    print("Listening on port %d" % BIND_PORT)

    httpd = http.server.HTTPServer(SERVER_ADDRESS, geocoding.handlers.GeoCodingRequestHandler)
    httpd.serve_forever()
